resources:
  - url: http://127.0.0.1:5000/area-card.js
    type: module
views:
  - cards:
      - type: custom:minimalistic-area-card
        title: "Kitchen"
        image: "https://demo.home-assistant.io/stub_config/kitchen.png"
        entities:
          - entity: sun.sun
